name: streamlit-conda-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - streamlit
  - geopandas
  - pandas
  - numpy
  - matplotlib
  - rasterio
  - shapely
  - gdal
  - fiona
  - pyproj
  - openpyxl
