name: streamlit-conda-env
channels:
  - conda-forge
dependencies:
  - python
  - streamlit
  - pandas
  - geopandas=1.0
  - numpy
  - matplotlib
  - rasterio
  - shapely
  - gdal
  - fiona
  - pyproj
  - openpyxl
