name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - rasterio
  - shapely
  - gdal
  - fiona
  - pyproj
  - openpyxl
